on: 
  push:
    branches:
      - "incus"
    tags:
      - "v*"
    
name: Upload Release Asset
jobs:
  build-and-upload-embedded:
    permissions: write-all
    name: Build & Upload Embedded
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

        # Note - Cannot use the setup action here as it uses a different yarn install arg
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

        # Build a tar that will be picked up by rancher builds and embedded into it
      - id: build-embedded
        name: Build Embedded
        run: ./scripts/build-embedded
        env:
          EMBED_PKG: https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3.tar.gz
          
      - id: Release-AIO
        name: Create Release With Asset
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          asset_files: ${{steps.build-embedded.outputs.BUILD_EMBEDED_TGZ}}

